workflows:
  android-build:
    name: Android Build V2 Force Cache Clean
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.22.3
      xcode: latest
      cocoapods: default
    scripts:
      - name: Flutter Clean
        script: |
          flutter clean
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches
          rm -rf build
      
      - name: Android Gradle Clean
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew clean
          cd ..
      
      - name: Get Packages
        script: |
          flutter pub get
          flutter pub deps
      
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
