name: infinite_puzzle
description: Infinite Puzzle Game with Avatar Shop
publish_to: "none"
version: 1.0.0+1
environment:
        sdk: ">=3.22.0 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
flutter:
  uses-material-design: true
  android:

